### ISSUE TITLE
sass based stylesheets

### ISSUE THREAD

**Issue by gambhiro** [asciidoctor/asciidoctor-epub3#114]
I would like to suggest converting the stylesheets in `data/styles` to sass format in a development folder `data/_sass`, and use that to generate the CSS in `data/styles`.

It would help ebook authors to create their custom alternatives of the basic theme. It could also provide mechanisms for #96.

My use case is that I would like to darken the colors in the theme -- but of course the color values relate to each other, so I started to convert the theme to SASS to be able to control the colors as variables.

Say, what would be easy for ebook authors, is to copy whatever is in `data/_sass`, then change a variable `$body-text-base`, generate the new CSS and related colors would change accordingly.

**Comment by gambhiro** [comment]
By the way, what is the function of `data/styles/color-palette.css` ? Is it simply there as a note to keep track of the colors, or is it used by something somewhere?

**Comment by mojavelinux** [comment]
> By the way, what is the function of data/styles/color-palette.css

That was just a development file for me to remember what colors I was using. I planned to eventually turn it into a color variables include, but I hadn't gotten that far.

**Comment by gambhiro** [comment]
I would be interested to know what you think about this business with sass stylesheets.

In general, do you like to make discussions in the issues or the PR threads?

**Comment by mojavelinux** [comment]
@gambhiro this has been my vision all along for the Asciidoctor EPUB3 stylesheet, so you anticipated my next move. The manual CSS with all the duplicate color values was only meant to be a temporary solution.

My only challenge is with the choice of tool. I've used most of the preprocessors, and I have decided that while I like SASS, I like stylus a whole lot more. Even better than stylus is to flip this on its head by using postCSS. Not only is that the direction the trend is heading, but I think it gives us the control where we really need it, which is in the postprocessing.

I'd like to try postCSS first and if that doesn't pan out, then stylus. SASS is my last choice.

We'll need to think about how to integrate this into the build process. It might be something that is done in a prepackaging step, because of course we need to ship a compiled stylesheet.

> In general, do you like to make discussions in the issues or the PR threads?

Issues. I think PR discussions should be scoped strictly to the implementation. While I like the use of a PR to give us something to talk about, the issue is the canonical discussion.

**Comment by mojavelinux** [comment]
...and if we do use SASS, I absolutely do not want to have Compass involved.

**Comment by gambhiro** [comment]
Thanks, PostCSS was new to me. I did some reading and some key points I gathered are:

- PostCSS (by default) still takes in CSS
- is an advanced++ tool, and an ebook stylesheet is not so complicated (shooting at pigeons with cannons?)
- there is a [stylus plugin](https://github.com/seaneking/poststylus)

I like the terse syntax (indentation, no braces, no semicolons) and it looks straightforward to redo the #115 work in stylus.

Shall I do that? It seems that with poststylus we can always add PostCSS on top of it for some specific feature if the need arises.

**Comment by gambhiro** [comment]
Closing in preference for #126.

**Comment by mojavelinux** [comment]
Sorry I fell behind on this thread. I've been having a hell of a busy week.

Thank you for porting your work over to Stylus. I'll check it out.

Here are my notes on your comments above.

> PostCSS (by default) still takes in CSS

Correct. Though what sets it apart is that it can take in modern and even experimental CSS and normalize it for older browsers. For example, it covers the vendor prefixing (via autoprefixer) that is common to preprocessors like Sass, LESS, and Stylus.

It also supports variables via CSS variables, which it can resolve when it compiles.

> is an advanced++ tool, and an ebook stylesheet is not so complicated (shooting at pigeons with cannons?

PostCSS is no more or less complicated in my opinion than any preprocessor. It's just doing the processing at a different stage. It's kind of like a polyfill for CSS 4 (and beyond).

> there is a stylus plugin

This raises the most important question. How should the processor be invoked? How will it be integrated into the build? What tools will be required?

The benefit of Sass is that it can be used directly from Ruby (a native gem compiled against libsass). All the other processors require the use of an external tool, regardless of whether there's a gem to wrap it.

To me, the stylus plugin is useless because it's just a wrapper. I'd much rather just execute the tool directly, either from the cli or in a Rake task. That means that to work with the stylesheets will require that you have stylus (and hence node). But I think that's okay. But we still need to decide when the compilation happens. In other words, what will the development workflow be. Let's discuss that in #126.
