### ISSUE TITLE
epubcheck raises warnings about preface files containing non-ascii chars

### ISSUE THREAD

**Issue by jnavila** [asciidoctor/asciidoctor-epub3#162]
If the book contains prefaces and dedications whose titles are translated and contain extended characters, these titles are used as the name of files in the archives.

For instance, with a title
```
[preface]
= Préface par Scott Chacon
```
yields

```
WARNING: progit_v0.epub/OEBPS/_préface_par_scott_chacon.xhtml: File name contains non-ascii characters: é. Consider changing filename
```

**Comment by slonopotamus** [comment]
You can assign [custom IDs](https://asciidoctor.org/docs/user-manual/#custom-ids) to chapter titles in order to change filenames inside EPUB archive.

This will result in `OEBPS/preface-par-scott-charon.xhtml`:
```
[[preface-par-scott-charon]]
= Préface par Scott Chacon
```

**Comment by slonopotamus** [comment]
Reported a bug to epubcheck: w3c/epubcheck#1097.

**Comment by jnavila** [comment]
> You can assign [custom IDs](https://asciidoctor.org/docs/user-manual/#custom-ids) to chapter titles in order to change filenames inside EPUB archive.
> 
> This will result in `OEBPS/preface-par-scott-charon.xhtml`:
> 
> ```
> [[preface-par-scott-charon]]
> = Préface par Scott Chacon
> ```

I don't really understand your point here. The issue is with the name of the file, not the id.

**Comment by slonopotamus** [comment]
1. According to spec, Unicode filenames are valid
2. I think that epubcheck warning is invalid, that's why I reported w3c/epubcheck#1097. If it is fixed, we do not need to fix anything on asciidoctor-epub3 side.
3. Rumours say that people successfully sent books with Unicode filenames inside to ebook publishers.
4. User has full control over filename via custom ID. If he decides that epubcheck has more weight than the spec, he has tools to adjust his document accordingly.

Thus, until w3c/epubcheck#1097 gets a resolution (either a fix or rejection), I plan to do absolutely nothing with this.

**Comment by slonopotamus** [comment]
@mojavelinux Could you please comment on this, I'm probably missing something?

**Comment by slonopotamus** [comment]
There's even a TODO in epubcheck that says that [PKG-012 should not be a warning](https://github.com/w3c/epubcheck/blob/v4.2.2/src/main/java/com/adobe/epubcheck/ocf/OCFFilenameChecker.java#L90).

**Comment by mojavelinux** [comment]
> I don't really understand your point here. The issue is with the name of the file, not the id.

Setting the ID alters the filename that is used in the EPUB archive. The ID determines the filename, not the source file.

**Comment by slonopotamus** [comment]
[EPUBCheck 4.2.3|https://github.com/w3c/epubcheck/releases/tag/v4.2.3] was just released and PKG-012 is no longer a warning.
