### ISSUE TITLE
Cross references from included subfiles not honored properly.

### ISSUE THREAD

**Issue by gdamore** [asciidoctor/asciidoctor-epub3#166]
I had a spine document that included chapter documents, which then had many sub includes (think a reference manual -- one chapter for section 3, and then one include file representing a man page for each document.

The problem I found is that cross references between nested include files have to be rewritten to refer to the chapter file, rather than the individual subfiles. 

For my own uses, I wrote a tool that preprocesses the files and does the "include" logic, resolving cross references itself, before handing off to asciidoctor.  This felt really unsavory, and I wish that the cross references between nested include files just worked like they do elsewhere.

**Comment by gdamore** [comment]
Looking again, I see #150 -- I suspect that this particular problem is a duplicate of that.

**Comment by mojavelinux** [comment]
> The problem I found is that cross references between nested include files have to be rewritten to refer to the chapter file, rather than the individual subfiles.

That's correct. That's because there is no such thing as a subfile in AsciiDoc (currently). Includes a preprocessor directives, so this is not something the cross references can "see". We have a special case for the spine just because we had to find a way to have multiple chapter files to fit with EPUB3 requirements. But beyond that, includes get folded into the parent document.
