### ISSUE TITLE
admonition layouts could be "improved"

### ISSUE THREAD

**Issue by gdamore** [asciidoctor/asciidoctor-epub3#167]
The way the epub generator generates admonitions is to create a paragraph using the css before attribute to inject an icon or label.

This leads to a vertical layout in the text that is less visually appealing than the way things appear in the PDF and HTML outputs.

I'm not sure what the best way to get a horizontal layout, with the admonition icon to the left of the text, would be.  Perhaps just a single row, two column table?

At any rate, I'm really interested in improving the epub aesthetic, because right now it falls short of the HTML and PDF results.  I was able to make some improvements with CSS adjustments, but I think this sort of problem needs to be addressed in the layout engine itself.

**Comment by mojavelinux** [comment]
Such a layout can be achieved using CSS alone. The ::before pseudo class can still contribute the icon cell. It's just necessary to change the display property on the admonition div to `table` and the display property on the pseudo element and the content div to `table-cell`. Then they will be side-by-side. You'll still need to adjust the margin/padding.

Of course, this is going to highly depend on what CSS the reader supports.

I really want to avoid using tables for this use case. It's very poor semantics and the goal with this converter is to produce very semantic HTML so that readers apps can best understand the content.

What I've learned in working with the EPUB3 format is that there's really a very limited of styles within which you can operate and have it work across devices. In fact, even what we have varies widely in how it renders. It's unbelievably costly to work on styles for EPUB3 for this reason. So I'm really reluctant to invest much more time in the default styles, unless it's to take styles away.

**Comment by gdamore** [comment]
I figured it out.  Thanks!  With some other styling changes I’ve almost got
identical output and styling between my PDF and ebooks.  This makes me very
very happy.  It looks good in ibooks.  Will have to see how it renders in
other devices.

**Comment by gdamore** [comment]
I think we can close this for now.
