### ISSUE TITLE
Feature request: Support for ToC in the output

### ISSUE THREAD

**Issue by Buzzardo** [asciidoctor/asciidoctor-epub3#174]
We're moving from producing Epub from Asciidoc by going through Docbook to producing Epub purely with Asciidoctor (to simplify our tool chain). One of the things we have lost in doing so is a table of contents at the start of the book. We'd like to get that back. You can see an example of our current output here: https://docs.spring.io/spring-boot/docs/2.0.1.RELEASE/reference/epub/spring-boot-reference.epub

The ToC does appear in the e-reader (only tested on MacBook at present) in the ToC button in the menu at the top. We'd like to have it at the beginning of the book, too, though.

If we could get a switch (perhaps an attribute that goes in the spine file) to enable that behavior, we'd really appreciate it.

**Comment by gdamore** [comment]
Best Practice for ebooks seems to be to include the HTML ToC... even though this seems silly to me, since modern ereaders all use a NAV or TCX meta-data for the table of contents.  (iBooks does this for example).

**Comment by audiofanatic** [comment]
This is perhaps more important for technical books where the table of contents may have a few levels. Some popular reader apps (looking at you iBooks) can't handle more than 2 levels, even though the epub spec doesn't have any such restriction. For a multi-part book, that means the nav toc can at best have just parts and chapters. If you try to include anything deeper, things go haywire and chapters or sections get promoted to the part level, etc. This is a long-standing issue for years, so is unlikely to be fixed. A technical book will frequently have sections and subsections, but you can't safely show those in your nav toc due to the corruption issue. But a detailed toc is still desirable, so being able to embed a full toc in the document itself would be particular desirable for these cases.

**Comment by slonopotamus** [comment]
Please, see #342. The problem is: it isn't clear how user is supposed to navigate to TOC file. When they first open the book, they will see TOC right after cover page. But what if they're already in the middle of the book, how do they navigate to TOC? Adding 'Table of contents' link to NAV/TCX that is a table of contents _itself_ is kinda strange.

**Comment by slonopotamus** [comment]
Do you have any real-world example of a ebook with inline TOC?

**Comment by craigscott-crascit** [comment]
An example I have on hand is _Large-Scale C++ Volume 1: Process and Architecture_ by George Lakos. It's nav shows the following:

* Cover Page
* About This eBook
* Half Title Page
* Title Page
* Copyright Page
* Dedication Page
* Contents
* Preface (with sub sections)
* Acknowledgements
* Then come the parts and chapters, etc.

**Comment by mojavelinux** [comment]
Putting an in-content TOC is clearly a preference. Some people will want it, others will not want it. There are good arguments for both. Therefore, I think it should be controlled by a setting.

The obvious choice is to honor to `toc` attribute. If set, the `toc` will be added to the content. If not set, it will only be defined in the metadata.

It's also reasonable to put more of the TOC in the metadata. The reason it only has two levels is historical (if memory serves me right).

**Comment by craigscott-crascit** [comment]
> It's also reasonable to put more of the TOC in the metadata. The reason it only has two levels is historical (if memory serves me right).

The Books app on macOS (presumably iBooks on iPad/iOS too then, haven't checked lately) makes a total mess of the TOC if there are more than two levels, even today. That's the main reason we need the ability to have a more detailed TOC directly in the document itself. 😞

**Comment by craigscott-crascit** [comment]
Actually that raises a related point. We would want to support different levels in the inlined TOC and in the nav. There's not any existing attribute that would allow you to do that, as far as I'm aware. With things as they currently are, I'm restricted to setting `toclevels` to 1 for epub so that I don't get more levels in the nav than all readers can support properly.

**Comment by slonopotamus** [comment]
@mojavelinux If you look at #342, you'll see that it does honor `:toc:` ;)

**Comment by mojavelinux** [comment]
> The Books app on macOS (presumably iBooks on iPad/iOS too then, haven't checked lately) makes a total mess of the TOC if there are more than two levels, even today.

It's really sad that the eReaders are still such a convoluted experience. If they honored the spec properly, we wouldn't need to shove the TOC directly in the content. But I understand that this is reality we're facing and we have to deal with it.

> If you look at #342, you'll see that it does honor :toc: ;)

That's great to hear!

**Comment by mojavelinux** [comment]
> Actually that raises a related point. We would want to support different levels in the inlined TOC and in the nav. There's not any existing attribute that would allow you to do that, as far as I'm aware. With things as they currently are, I'm restricted to setting toclevels to 1 for epub so that I don't get more levels in the nav than all readers can support properly.

The way Asciidoctor PDF handles this is that it treats the metadata TOC as the "outline". So there is "outline" and "outlinelevels" as a parallel to "toc" and "toclevels". So outline=metadata, toc=inside content. This works pretty well.

**Comment by slonopotamus** [comment]
> It's also reasonable to put more of the TOC in the metadata. The reason it only has two levels is historical

Actually, our current metadata TOC depth is controlled by `:toclevels:`.

**Comment by slonopotamus** [comment]
> it isn't clear how user is supposed to navigate to TOC file

Answering to myself: via landmark.

**Comment by slonopotamus** [comment]
Okay, so.

1. We add `:outlinelevels:` attribute that will control depth of metadata TOC. When `:outlinelevels:` is not set, it defaults to `:toclevels:`
2. When `:toc:` is set, we will generate a _second_ TOC file with possibly different depth and add it to book spine.
3. We add support for landmarks so user has a way to navigate to inline TOC.

**Comment by slonopotamus** [comment]
@mojavelinux @Buzzardo @craigscott-crascit @gdamore Anyone wants to review #342 before it hits `master`?

**Comment by slonopotamus** [comment]
Further work on custom TOC placement will be done in #344.

**Comment by Buzzardo** [comment]
Thanks much. :)
