### ISSUE TITLE
Image and listing numbers are reset in each chapter document

### ISSUE THREAD

**Issue by eiswind** [asciidoctor/asciidoctor-epub3#178]
I set up a spine as suggested, that includes several chapter files.
I see that the listing and image numbers are reset for each file. With the pdf backend they are handled correctly.

Is there any way to handle this?

`
= Title
Thomas Kratz
:doctype: book
:encoding: utf-8
:icons: font
:data-uri:
:toc:
:imagesdir: ./images

include::intro.adoc[leveloffset=+1]

include::hello.adoc[leveloffset=+1]

include::api.adoc[leveloffset=+1]

`

**Comment by mojavelinux** [comment]
This is an artifact of Asciidoctor EPUB3 originally being designed for a magazine. We've since designated a publication type attribute, which would allow us to have separate behavior for books.

Ideally, the images would be numbered by chapter, as in `Figure 1.1`. However, Asciidoctor core doesn't yet have support for that. So we could either move forward by just using straight numbering, or wait for core to provide chapter-based numbering.

**Comment by eiswind** [comment]
I would be happy with straight numbering, is that already possible?

**Comment by mojavelinux** [comment]
It's not currently possible. Each chapter is converted as a separate document. However, it *could* be possible if the necessary change was made. That would mean passing in the last number used to influence the starting number for the next chapter.

**Comment by slonopotamus** [comment]
@mojavelinux where 'last assigned number' is stored? Some document attribute?
