### ISSUE TITLE
Inline anchors are missing their ids

### ISSUE THREAD

**Issue by michaelpj** [asciidoctor/asciidoctor-epub3#201]
In the epub output I'm getting a nice chapter for the bibliography, but it's generating anchor links with empty ids, like so:
```
<span class="principal">[<a id=""></a>] ... </span>
```

**Comment by michaelpj** [comment]
They come out fine in the HTML version.

**Comment by michaelpj** [comment]
Hm, if I add extra explicit anchors in a bib entry with `[[anchor]]`  they *also* get empty ids, so something is very funny here.

**Comment by michaelpj** [comment]
Narrowing further: any anchors inside list items of any kind are missing ids.

**Comment by michaelpj** [comment]
Okay, I can't get any inline anchors of any kind to work!

**Comment by michaelpj** [comment]
I made some progress on this:
- Harmonizing the converter code with that for the html5 converter in a few places helped, in particular the case for `:ref` in `convert_inline_anchor` wasn't adding the id when it should. That fixed the anchors not having ids.
- For some reason, anchors in a bibliography chapter aren't getting put in the document's catalog (it's actually completely empty apart from the section anchor!). So the generated links actually work, but we get a lot of warnings about them pointing to unknown anchors. I haven't figured this out yet.

I'll put up a PR for the first half, if anyone has any bright ideas about the second half that would be welcome!

**Comment by mojavelinux** [comment]
Excellent news!

> anchors in a bibliography chapter aren't getting put in the document's catalog (it's actually completely empty apart from the section anchor!). So the generated links actually work, but we get a lot of warnings about them pointing to unknown anchors. 

Based on what you wrote above, it seems the problem is that you are using the double bracket syntax for anchors instead of the triple bracket syntax. For reasons that have to do with how AsciiDoc was originally implemented, bibliography anchors must use triple brackets (e.g., `[[[name]]]`).

**Comment by michaelpj** [comment]
No, we are using the triple brackets. It's very weird - it all works fine in the html output, so it's not a bug in core, it must be something in this gem.

**Comment by michaelpj** [comment]
BTW, I suspect there's a good reason not to do this, but seems worth asking: would it make sense to make the epub3 converter a subclass of the html5 converter? They have a lot in common, and in this case I fixed part of the issue by copying the (probably more widely used and tested) code from the html5 converter.

**Comment by mojavelinux** [comment]
It didn't used to be possible to subclass the built-in converters. A ton has changed since this converter was developed, so that's now a very real possibility. However, it will require a major version bump, so I think we need to find our way to 2.0.0 in order for that to happen (much like the path the PDF converter is currently on).

> it all works fine in the html output, so it's not a bug in core, it must be something in this gem.

I wouldn't doubt it as this converter is very old. It's in need of a lot of work to bring it up to speed with what's been going on in core.

**Comment by michaelpj** [comment]
> I wouldn't doubt it as this converter is very old. It's in need of a lot of work to bring it up to speed with what's been going on in core.

Yeah, I can see that things have changed, but I'm not quite confident enough to offer a more thorough refactoring, so I'm just going to see if I can find a targeted fix.

**Comment by michaelpj** [comment]
Phew, I think I tracked it down. It's an interaction between core and `asciidoctor-epub3`'s include processor. I've described it in https://github.com/asciidoctor/asciidoctor/issues/3356 - I think ultimately it should be fixed in core.

**Comment by michaelpj** [comment]
For the moment I can work around this with my PR applied and putting the bibliography inside another section, i.e.

```
= Dummy section

[bibliography]
== Bibliography

- [[[item]]] This works now
```

**Comment by michaelpj** [comment]
See https://github.com/asciidoctor/asciidoctor-epub3/issues/205 for the second half.

**Comment by mojavelinux** [comment]
Another solution, as I mentioned elsewhere, is to put the bibliography style directly on the list.

```
= Bibliography

[bibliography]
- [[[item]]] This works now
```

Since Asciidoctor EPUB3 calls for the special document arrangement, I think it's reasonable that it be the one to normalize the section style so it can be used without this modification to the document (and, in turn, semantics).

**Comment by mojavelinux** [comment]
Keep in mind, that workaround won't produce valid DocBook, but if the focus is on AsciiDoc to EPUB3 conversion, that doesn't matter. You could also write it as:

```
ifndef::backend-epub[]
[bibliography]
endif::[]
= Bibliography

[bibliography]
- [[[item]]] This works now.
```

That would make it work in all environments.
