### ISSUE TITLE
`Image not found or not readable` if `imagesdir` is not in the current directory

### ISSUE THREAD

**Issue by jninja** [asciidoctor/asciidoctor-epub3#22]
If you set `imagesdir` with something like:

```
:imagesdir: ../commons/images
```

You receive `Image not found or not readable` error.

**Comment by danhyun** [comment]
I've found that you must provide absolute path, which doesn't jive well with html5 or pdf outputs.

```
:imagesdir: images
```

> asciidoctor: WARNING: could not embed image; images/D:/books/book/src/asciidoc/images/group_shot.jpg not found

**Comment by mojavelinux** [comment]
At some point we broke being able to set the imagesdir to a value other than "images". We need to reenable this feature and also document any requirements for organizing files in the project.

**Comment by mojavelinux** [comment]
I've thought about this and the problem is that `imagesdir` cannot be both the relative path to the image inside the archive and the path to the image on disk if outside of the document directory. In other words, to use a single attribute, it must represent the same relative path both in the archive and on disk.

If we want to be able to allow the images "catalog" to be outside of the document directory, then we either need to have two separate attributes or all the image paths in the archive need be rewritten. I'm not really opposed to the second alternative since it really doesn't matter to you where the images are inside the archive, so long as they don't conflict. However, it will require some decorator logic to allow the imagesdir attribute to be used to create a reference to the image and to find it on disk.

As it stands now, the imagesdir must point to a location inside the directory of the spine document.

**Comment by mojavelinux** [comment]
And to be clear, you should not specify an absolute path. It must be a relative path.

**Comment by slonopotamus** [comment]
I want to make scope of this task more clear: we're talking about the case where structure is:

```
|
+- spine.adoc
|
+- images/
| |
| +- image.png
|
+- chapters/
  |
  +- chapter.adoc
```

And `chapter.adoc` has `:imagesdir: ../images`

But we're not talking about a case where `:imagesdir:` is outside of spine directory.

**Comment by slonopotamus** [comment]
Okay, I don't actually like it. `:imagesdir:` is normally resolved relative to root document. Such construct would not work properly with HTML, I don't see why asciidoctor-epub3 should handle `:imagesdir:` in a different way. The more we're compatible with other backend, the happier users because they can produce different formats from the same source.

**Comment by slonopotamus** [comment]
Quoting [docs](https://github.com/asciidoctor/asciidoctor-epub3#working-with-images):

> The images catalog is defined by the imagesdir attribute. If set, **the value of this attribute is resolved relative to the spine document and must be at or below (i.e., within) the directory of that document**. (In other words, it cannot point to a location outside the document directory).
