### ISSUE TITLE
[alpha.18] invalid part, must have at least one section (e.g., chapter, appendix, etc.)

### ISSUE THREAD

**Issue by cexbrayat** [asciidoctor/asciidoctor-epub3#365]
We started to see errors like the following in the log of our builds when bumping to alpha.18:

```
asciidoctor: ERROR: main.adoc: line 17: invalid part, must have at least one section (e.g., chapter, appendix, etc.)
```

This does not prevent the build from emitting the epub (and I think it is fine). But it's intriguing to see that error in the log.

See https://github.com/cexbrayat/repro-invalid-part for a tiny repro.

**Comment by slonopotamus** [comment]
This message [comes from Asciidoctor core](https://github.com/asciidoctor/asciidoctor/blob/v2.0.10/lib/asciidoctor/parser.rb#L429).

Asciidoctor is not happy because your section structure violates [the rules](https://asciidoctor.org/docs/user-manual/#book-parts-and-chapters):
> Each part must contain at least one section (a chapter or special section).

**Comment by slonopotamus** [comment]
I believe you want to remove `ifndef::ebook-format[:leveloffset: 1]` from `main.adoc`.

**Comment by cexbrayat** [comment]
Thank you for your quick answer.

This document is a base to generate HTML, PDF and EPUB outputs, that's why there is a condition for leveloffset (it was suggested by Dan a long time ago). If I use `:leveloffset: 1`, it does work without error indeed.

So maybe the issue is that the condition is no longer properly applied? Something change recently in that area?

**Comment by slonopotamus** [comment]
I believe this is a side effect of #302. Asciidoctor EPUB3 got rid of a bunch of custom include processing logic and now treats document as a whole like all other backends do. So, there's nothing wrong with error message, it's just old Asciidoctor EPUB3 were doing things that allowed invalid Asciidoctor documents (even worse, it *required* them to be invalid, that's why you had conditional EPUB3-specific logic).

If you try removing `:leveloffset: 1`, you'll see that you get exactly the same error for other backends too (HTML/PDF).

**Comment by cexbrayat** [comment]
Ha, nice to know! I thought it was still mandatory to have different structures depending on the format.
I'll close this then, thanks.
