### ISSUE TITLE
chapter title looks too small

### ISSUE THREAD

**Issue by funnygerman** [asciidoctor/asciidoctor-epub3#388]
I create a book containing several chapters. All of them starting like this
[#ChapterNr]
= Chapter title

However if I generate the book all chapter titles looks just to small (at least in Apple Books on a Mac), see screenshot

<img width="541" alt="grafik" src="https://user-images.githubusercontent.com/2098186/104783604-af1bc900-5786-11eb-804b-f808668eb856.png">

I tried to play with css, but without success. The size remains the same.

What do I wrong? Or if I'm doing everything right, how can I change the size?

**Comment by slonopotamus** [comment]
@funnygerman could you please try reverting ffe8356b45552ace21d770002c9ddbc7e9e534ef and checking whether that fixes the issue?

**Comment by slonopotamus** [comment]
@funnygerman also, please set `:doctype: book`. By default, it is article.

**Comment by slonopotamus** [comment]
I also would like to see document source. That title needs to have `==` instead of `=` (because `=` is document title). And if you really used `=`, Asciidoctor would provide an `level 0 sections can only be used when doctype is book` error during conversion. And looks like this is exactly what happened. In this scenario, we produce a bogus `<h0>` tag that renders in smaller font than main text.
