### ISSUE TITLE
Images cannot float in EPUB rendering

### ISSUE THREAD

**Issue by Thanatermesis** [asciidoctor/asciidoctor-epub3#405]
When trying to align an image with text is not possible, I have tried all the possible options without success
Example code:

```
== Test section
.Title for image
image::einstein-relatividad.jpg[,340,role="related thumb left"]
Lorem Ipsum is simply dummy text of the printing a.....
```

----
So the HTML rendering (asciidoctor) renders very good, like:

# HTML:

![image](https://user-images.githubusercontent.com/1181626/127756927-5555d966-7266-4418-9740-71d42f52a88c.png)

----
But for PDF or for EPUB3, it always renders it in a strange and unfriendly way (I tried different options for the images, nothing found to work nicely yet):

----
# Epub:

![image](https://user-images.githubusercontent.com/1181626/127756941-c2913d33-38bf-4a66-8f04-ec5ca5f7a0bc.png)

----

# PDF:
![image](https://user-images.githubusercontent.com/1181626/127756950-1cc2405b-72f3-4c6d-8b51-2b7dd9c6d89e.png)

**Comment by mojavelinux** [comment]
Can you please repost your entire report here?

**Comment by Thanatermesis** [comment]
done

**Comment by mojavelinux** [comment]
My advice here would be to go ahead and add the same styles that are present in the [default stylesheet](https://github.com/asciidoctor/asciidoctor/blob/master/src/stylesheets/asciidoctor.css). The reason I didn't add them originally is because many ePUB readers won't honor them. But that's really up to the writer to decide whether to use layouts that are only supported in a handful of ePUB readers. Caveat emptor.

**Comment by Thanatermesis** [comment]
So what would happen in the case an epub reader (let's say "kindle") cannot read this style? it just switches to the default mode ? (first image, then text) or it directly don't show it? so if fallbacks to a different styling i don't see the problem

**Comment by mojavelinux** [comment]
It would just ignore the request to float the image and display it as it currently appears.
