### ISSUE TITLE
Formatting pairs don't work in externalized footnotes

### ISSUE THREAD

**Issue by georgerbr** [asciidoctor/asciidoctor-epub3#409]
Hi,
I'm running

```
$ asciidoctor-epub3 -V
Asciidoctor EPUB3 1.5.1 using Asciidoctor 2.0.10 [https://asciidoctor.org]
Runtime Environment (ruby 2.7.0p0 (2019-12-25 revision 647ee6f091) [x86_64-linux-gnu]) (lc:UTF-8 fs:UTF-8 in:UTF-8 ex:UTF-8)

$ asciidoctor -v --trace footnotes_with_formatting.adoc
$ asciidoctor-epub3 -v --trace footnotes_with_formatting.adoc
```

and the formatting in the following source won't work in the externalized footnote, whereas in the regular one it will:

```asciidoc
= Footnotes with formatting
:doctype: book

:fn-disclaimer: footnote:[Opinions are *my* _own_.]

This footnote won't have formatting.{fn-disclaimer}
This one will.footnote:[Opinions are *my* _own_.]
```

The problem occurs both with EPUB and HTML output.

![epub_output](https://user-images.githubusercontent.com/4930759/136044302-d9e1f9a7-4c9f-4482-941b-03b7306a0fac.png)

![html_output](https://user-images.githubusercontent.com/4930759/136044331-6d6925d7-9407-4d71-9db1-602726f01846.png)

**Comment by mojavelinux** [comment]
What you're describing is consistent with AsciiDoc's design. This is not a bug.

If you want to include text formatting in an externalized footnote, you must wrap the attribute entry in an inline pass macro to enable the quotes substitutions. Otherwise, the formatting marks are not interpreted.

```
= Footnotes with formatting
:doctype: book
:fn-disclaimer: pass:c,q[footnote:[Opinions are *my* _own_.]]

This footnote *will* have formatting.{fn-disclaimer}
```

The "c" retains the substitution of special characters and the "q" enables text formatting (aka quotes)

I will add an example to the following section so this is more clear: https://docs.asciidoctor.org/asciidoc/latest/macros/footnote/#externalizing-a-footnote

**Comment by georgerbr** [comment]
> 
> 
> This tip has been added to the documentation. See https://docs.asciidoctor.org/asciidoc/latest/macros/footnote/#externalizing-a-footnote

Thanks for clarifying! Works great!
