### ISSUE TITLE
Table of Contents renders as Untitled in eBook readers other than iBooks

### ISSUE THREAD

**Issue by mraible** [asciidoctor/asciidoctor-epub3#42]
In iBooks, the .epub file generated works great, looks great and the ToC shows up as expected. However, when using other readers, all the chapter titles render as "Untitled". I've tried Clearview:

<img width="1312" alt="clearview" src="https://cloud.githubusercontent.com/assets/17892/10825360/50871510-7e2a-11e5-8207-91092245aa64.png">

And Calibre:

<img width="1023" alt="calibre" src="https://cloud.githubusercontent.com/assets/17892/10825366/54c7859c-7e2a-11e5-925e-d2dfc658a6e8.png">

And Kibatu:

<img width="1399" alt="kibatu" src="https://cloud.githubusercontent.com/assets/17892/10825373/595afa30-7e2a-11e5-837b-38ca369d0e9f.png">

In Kibatu, images don't render either. The following error pops up.

<img width="688" alt="kibatu-images" src="https://cloud.githubusercontent.com/assets/17892/10825382/633473b0-7e2a-11e5-95b4-27a853790892.png">

**Comment by mojavelinux** [comment]
I'll need to review the jhipster book source to know what's going on. What I suspect is that Asciidoctor EPUB3 isn't recognizing the structure and therefore not finding the chapter partitions. Asciidoctor EPUB3 uses the source code structure rather than the AST to find the chapter divisions (that's just how it works atm). We'll likely find another way to do this in the future, but that was the stopgap solution we came up with for chunking the chapters. In short, include == chapter == TOC entry.

**Comment by mojavelinux** [comment]
Is the book source public? If not, could you give me access to the repo for investigation?

**Comment by mraible** [comment]
No, it is not. I'll add you to the repo.

**Comment by mojavelinux** [comment]
Thanks! I'm looking into it.

**Comment by mojavelinux** [comment]
As I suspected, Asciidoctor EPUB3 requires that each chapter be a standalone AsciiDoc document (it starts with a doctitle). The first heading in each chapter file must be a doctitle, not a level-1 heading.

One way to quickly get this working is to define `leveloffset` in the header of index.adoc as follows:

```
ifndef::ebook-format[:leveloffset: 1]
```

Then you need to remove one level from every heading in the book. That way, each chapter is a standalone file for EPUB3 (starts with a doctitle), but will be exactly as it was for every other backend.

We need to find a way in Asciidoctor EPUB3 to work with chapter files that use a level-1 heading instead of a doctitle. But again, this was a stopgap solution for the environment Asciidoctor EPUB3 was originally created (where each chapter was a top-level AsciiDoc file).

**Comment by mojavelinux** [comment]
> In Kibatu, images don't render either. The following error pops up.

This is because you are using `data-uri`, which that reader doesn't seem to support. I realize that `data-uri` is your workaround for getting inline images to work...but that's really just a temporary solution anyway until we can get that other issue resolved properly. We shouldn't have to use `data-uri` in the EPUB3 backend.

**Comment by mojavelinux** [comment]
Now that I have the book source I can play around with trying to find a better solution to the images problem.

**Comment by mojavelinux** [comment]
Here are details about the required layout for Asciidoctor EPUB3. https://github.com/asciidoctor/asciidoctor-epub3#declaring-the-spine That could probably be explained better. I also think we can get rid of that limitation eventually.

**Comment by mraible** [comment]
I tried adding `ifndef::ebook-format[:leveloffset: 1]` to index.adoc and removing a '=' character from all files that aren't `index.adoc`. The good news is this makes it so the ToC works in readers other than iBooks. However, instead of having "JHipster's" in the ToC, it has "JHipster&#8217;s" and those titles fail to link to the content.

The bad news is it causes iBooks to fail - it thinks the document is corrupt. 

So it works great in iBooks w/o any modifications and if try to make it work in other readers, it breaks iBooks. :-/

**Comment by mojavelinux** [comment]
If you put a backslash before the single quote I think it will prevent AsciiDoc from converting it to a smart quote. Is it the smart quote that makes the file corrupt in iBook or is that a separate issue?

**Comment by mojavelinux** [comment]
In other words:

```
== JHipster\'s UI Components
```

This is definitely something we'll want to fix in Asciidoctor EPUB3. Those titles should be substituted properly. I'll have to look at what the requirements are for navigation entries.

**Comment by mojavelinux** [comment]
Oh, it is possible to fix the linking by giving the chapter an explicit id. The auto-generated id isn't removing special characters like it should.

```
[#jhipsters-ui-components]
== JHipster\'s UI Components
```

That will fix the linking and should prevent iBooks from crashing. I bet it doesn't like the single quote in the file name (you can see this by opening the epub file with vim or something else).

**Comment by mojavelinux** [comment]
Sorry, you have to write it as:

```
[[jhipsters-ui-components]]
== JHipster\'s UI Components
```

I guess it looks for only the old-style syntax.

**Comment by mojavelinux** [comment]
In all, the header should look like this:

```
[[jhipsters-ui-components]]
= JHipster\'s UI components
:imagesdir: images
```

**Comment by mraible** [comment]
Here's the strange thing - if I make no changes, the ToC (and titles with apostrophes) work fine in iBooks.  It's when I make the `:leveloffset: 1` change and remove a `=` that iBooks stops working. I'm not sure if iBooks is the one to target, or another reader is better to test in.

**Comment by mraible** [comment]
FWIW, I only define `:imagesdir:` in chapters to workaround a bug in AsciidocFX.

**Comment by mojavelinux** [comment]
Gotcha. I was just showing you where it had to be if included relative to the id and title.

Asciidoctor EPUB3 is very picky about how it parses these files because we're using a very quick scan to extract information rather than a full parse. You can see where this happens here: https://github.com/asciidoctor/asciidoctor-epub3/blob/master/lib/asciidoctor-epub3/spine_item_processor.rb#L18-L23

**Comment by mojavelinux** [comment]
The `\'` is only required to fix the display of the toc entry (the EPUB2 navigation file, which most readers still use). The rest of the problem should be solved by assigning an explicit ID to the chapter title.

**Comment by mojavelinux** [comment]
I filed an issue to deal with cleaning the auto-generated id and the display of the TOC entry. See #46.

**Comment by mraible** [comment]
I think I figured out enough to close this issue. By moving all the titles in included pages up a level, I'm able to see them in the EPUB. If I include `ifndef::ebook-format[:leveloffset: 1]`, it causes issues with iBooks. It doesn't seem to be needed.

Removing `:data-uri:` solves the images problem.

**Comment by mojavelinux** [comment]
> If I include ifndef::ebook-format[:leveloffset: 1], it causes issues with iBooks.

That's really strange that this affects iBooks because it should only kick in if not generating and epub. So it should be the same as it not being there at all. One way to be sure of this is to reverse the logic:

```
ifdef::backend-html5,backend-pdf[:leveloffset: 1]
```

That should make what is happening more clear.

If you don't make this correct, I don't think the PDF will generate correctly (on the other hand, maybe it will because the PDF is treating parts and chapters the same right now).

**Comment by mraible** [comment]
Nevermind about `[:leveloffset: 1]`, it's not needed for EPUB, but it's needed for PDF and HTML5. Once I added those backends back into my build, I started getting errors. 

```
ERROR: chapters/preface.adoc: line 1: invalid part, must have at least one section (e.g., chapter, appendix, etc.)
asciidoctor: WARNING: chapters/preface.adoc: line 11: section title out of sequence: expected level 2, got level 1
asciidoctor: WARNING: chapters/preface.adoc: line 15: section title out of sequence: expected level 2, got level 1
asciidoctor: WARNING: chapters/preface.adoc: line 19: section title out of sequence: expected level 2, got level 1
asciidoctor: WARNING: chapters/preface.adoc: line 23: section title out of sequence: expected level 2, got level 1
asciidoctor: WARNING: chapters/preface.adoc: line 88: section title out of sequence: expected level 2, got level 1
asciidoctor: ERROR: chapters/chapter2.adoc: line 1: invalid part, must have at least one section (e.g., chapter, appendix, etc.)
asciidoctor: ERROR: index.adoc: line 48: invalid part, must have at least one section (e.g., chapter, appendix, etc.)
````

The only issue now is the ToC in PDF and HTML5 show a lot more items, but maybe that's a good thing. ;)

**Comment by mraible** [comment]
Just discovered the "more items in the ToC" issue was caused by my faulty find-and-replace logic.

**Comment by mojavelinux** [comment]
:)

**Comment by mojavelinux** [comment]
You should add a custom ID for the Action! chapter as well:

```
[[action]]
= Action!
```

**Comment by meisterluk** [comment]
Sorry, what is the current state of the issue?

I get the same problem. `ifdef::backend-html5,backend-pdf[:leveloffset: 1]` does not help unless you are looking for more printed warnings like @mraible mentioned (`section title out of sequence: expected levels 0 or 1, got level 2`). I create an EPUB file and the level-0 header with every level-1 header is an individual `Untitled` entry in calibre.

**Comment by mojavelinux** [comment]
Have you organized your chapters as separate include files?

**Comment by mojavelinux** [comment]
Please refer to the sample for reference: https://github.com/asciidoctor/asciidoctor-epub3/blob/master/data/samples/sample-book.adoc

**Comment by meisterluk** [comment]
Yes, I have organized them as separate include files.

The sample provides the desired TOC representation in calibre:
![calibre](https://user-images.githubusercontent.com/358358/30823565-db1c939e-a22c-11e7-83ac-e47d8990b7bf.png)

It seems the "Untitled" occurs because every included file is parsed individually meaning that headers in an included file must begin with level-0 headers. I assumed (due to the description below), that a level-0 header in the main file must be proceeded by a level-1 header in the included file.

> It’s important to understand that the include directive is not aware of the document structure. It effectively copies the content from the other file and pastes it at the location of the include directive. This is called a preprocessor operation.
via http://asciidoctor.org/docs/user-manual/#include-directive

This description is IMHO orthogonal to what this description says. Preprocessor refers to tools like m4 which literally copy and paste content to create programs. So either this is a bug or the tutorial is wrong.
