### ISSUE TITLE
Should revdate support spelling of months in non-English locales?

### ISSUE THREAD

**Issue by ielfretter** [asciidoctor/asciidoctor-epub3#423]
Hi,

If I parse the following tiny module:

`:worktitle:`

Using this command line:

`asciidoctor-epub3 -a worktitle=foobar -a lang=en -a revdate='4 october 2022' debug.adoc`

Then there is no problem. But when I switch to the Dutch locale (note we spell october differently):

`asciidoctor-epub3 -a worktitle=foobar -a lang=nl -a revdate='4 oktober 2022' debug.adoc`

I get the following:

`asciidoctor: ERROR: debug.adoc: failed to parse revdate: argument out of range`

What do you guys think? Should revdate support spelling of months in non-English locales?

**Comment by slonopotamus** [comment]
asciidoctor-epub3 needs a _machine-readable_ date that it will pass to EPUB metadata. Currently, it tries to parse date using Ruby standard `DateTime` class.

So, I'd even recommend avoiding English words in `revdate` and instead using ISO8601 YYYY-MM-DD format.

**Comment by ielfretter** [comment]
Cheers. I followed that path and made the appropriate changes even before you suggested it. Would you consider it a bug though? I'm asking, because when I run the same example on `asciidoctor` instead, there is no such error.

**Comment by mojavelinux** [comment]
I believe slonopotamus is right that the intent here to provide the date in a parseable (non-local) format. It works with the asciidoctor command since that command doesn't need to use the date for anything. It just passes it right through. So just because it is quite doesn't mean it is right. When there's a need for a real date, like in the case of EPUB3, you need to put valid information in this field.

**Comment by ielfretter** [comment]
Cheers Dan. That settles it then.
