### ISSUE TITLE
images in tables are not pulled into the archive

### ISSUE THREAD

**Issue by LightGuard** [asciidoctor/asciidoctor-epub3#5]
You can recreate this by building the book at https://github.com/vromero/mule-doc/commit/4eed0f12107f9db650a4243727f137070c4ce774. The list discussion is at http://discuss.asciidoctor.org/Asciidoc-EPUB3-and-local-images-td1936.html

**Comment by mojavelinux** [comment]
I've decided to solve this by using the document catalog instead of the AST. We already have the limitation that the imagesdir cannot be changed within a chapter file, so we have enough information to be able to reconstruct the path to the image from the value in document catalog alone.

In order to make this work, we have to set the catalog_assets option on the document to true. Fortunately, we control the loading of each chapter file in the spine processor, so we can set additional options. (See https://github.com/asciidoctor/asciidoctor-epub3/blob/9c241f63c2197667e17ead6f6aa51ef48ade0ebc/lib/asciidoctor-epub3/spine_item_processor.rb#L50-L58).

One problem we're going to run into is that, as of 1.5.6.1, core does not pass the catalog_assets option to nested documents (e.g., an AsciiDoc table cell). There's no easy way around this limitation. Therefore, images in AsciiDoc table cells will not be included until that is fixed in core (slated for 1.5.7).

**Comment by mojavelinux** [comment]
I also needed to add SVG support for inline images in the converter and set a max-width value for inline images. I decided to add the class `inline` to inline images to help distinguish them from block / figure images in the stylesheet.

**Comment by mojavelinux** [comment]
Please note if you are reading this that images in tables will not be included unless you are using at least Asciidoctor (core) 1.5.7 (and it has been released, of course).
