### ISSUE TITLE
Problem installing from git

### ISSUE THREAD

**Issue by mozgwar** [asciidoctor/asciidoctor-epub3#64]
Hi,
I'm getting the following error:
gem install pkg/asciidoctor-epub3-1.5.0.dev.gem 
ERROR:  While executing gem ... (Gem::Package::PathError)
    installing into parent path /home/mathieu/.gem/ruby/2.3.0/README.adoc of /home/mathieu/.gem/ruby/2.3.0/gems/asciidoctor-epub3-1.5.0.dev is not allowed

**Comment by mojavelinux** [comment]
You have some sort of permission or path problem with your gem setup. I doubt if you could install any gem if you are getting this sort of error.

Are you using RVM? If not, I highly recommend that you do so because it sets up Ruby properly.

To help you debug, please post the output of the following command:

```
gem env
```

**Comment by mojavelinux** [comment]
Btw, it's simpler to use the `install:local` command to build and install the gem.

```
rake install:local
```

I've updated the instructions in the README accordingly.

**Comment by mozgwar** [comment]
Ok thanks. I'm using arch linux and it comes with ruby 2.3.0 by default. So when I installed ruby 2.2
under rvm the problem was gone

**Comment by mojavelinux** [comment]
It's for this reason that I always recommend using RVM (or something equivalent) when using Ruby for development (or other user-space programs). The system Ruby is for system-wide applications (installed and managed by a package manager). If you are doing something in your home directory, then you don't want to be using the system Ruby. (And few distributions setup Ruby correctly so that you can use the `gem` command reliably with the system installed Ruby). Basically, just assume you don't have Ruby and that you need RVM to get it. That's my personal policy and it works for me 100% of the time.

**Comment by mojavelinux** [comment]
I posted this advice here: https://plus.google.com/114112334290393746697/posts/1RrCjymHdBw
