### ISSUE TITLE
Authors include Asciidoctor

### ISSUE THREAD

**Issue by cexbrayat** [asciidoctor/asciidoctor-epub3#68]
The author of our ebook is "Ninja Squad":

```
= Become a ninja with Angular2
:author:    Ninja Squad
```

However, the epub and mobi metadata are saying : "Ninja Squad & Asciidoctor".
The main document include several other documents (one per chapter).

Is this a bug or am I missing a configuration option?

**Comment by mojavelinux** [comment]
You'll need to add the `creator` attribute to the document header of the spine (as mentioned in the README).

`creator` - Populates the creator (`<dc:creator>`) in the package metadata. If the creator is not specified, the value of "Asciidoctor" is used.

Technically, the reader is not supposed to show this information in the author line because the role is marked as "manufacturer". However, that would be assuming too much about the competence of most of the reader applications ;)

We probably need to rethink some of these defaults when writing the metadata, but that should at least fix your immediate problem.

**Comment by cexbrayat** [comment]
That solves it indeed, thanks for the help!

**Comment by mojavelinux** [comment]
Documented in the README.
