### ISSUE TITLE
:front-image-cover not working

### ISSUE THREAD

**Issue by otavio** [asciidoctor/asciidoctor-epub3#77]
The front cover is not being set.

We tried to use different options in:

https://github.com/CollaborativeWritersHub/heading-for-the-yocto-project/blob/master/book/Heading-for-the-Yocto-Project.adoc

and it still does not work.

Is it a known issue?

**Comment by mojavelinux** [comment]
You are being bit by the blank line in your AsciiDoc header problem. In fact, none of the attributes you specified are part of the header, so they don't get recognized. The AsciiDoc header must not have any blank lines.

Also note that multiple authors must be separated by a semi-colon, not a comma.

Finally, you need to set the imagesdir per chapter if you are going to organize your images by chapter.

Here's the revised document:

```
= Heading for the Yocto Project
Otavio Salvador; Daiane Angolini
v1.0, 2016-09-08
:doctype: book
:toc: left
:toclevels: 2
:front-cover-image: image:cover.png[]

include::preface.adoc[]

:imagesdir: 01-The-Yocto-Project/images
include::01-The-Yocto-Project/chapter.adoc[]

:imagesdir: 02-Benefits-for-your-products/images
include::02-Benefits-for-your-products/chapter.adoc[]

:imagesdir: 03-Heading-for-Yocto-Project/images
include::03-Heading-for-Yocto-Project/chapter.adoc[]

:imagesdir: 04-The-Yocto-Project-community-ecosystem/images
include::04-The-Yocto-Project-community-ecosystem/chapter.adoc[]
```

As the documents are currently structured, the table of contents in the EPUB file isn't going to work. You need to adhere to the recommendation here: https://github.com/asciidoctor/asciidoctor-epub3#declaring-the-spine

---

I also recommend not putting Gemfile.lock in the git repository (especially when one of the gems references a git repository). This tripped me up for awhile because it kept fetching an old version of Asciidoctor PDF.

**Comment by otavio** [comment]
I am closing this to-do as it does fixes the cover issue. I will add specific items for other issues. Thanks for the help.

**Comment by mojavelinux** [comment]
Great!
